* xdispswitch

=xdispswitch= picks up the active X11 window and moves it to the next
Xinerama monitor it can find. It will try to preserve the
monitor-relative size and position, avoid stepping on any window
manager panels, and generally not make a mess. Bind it to a key and
take control of your windows.

(I used to use a GNOME 3 shell extension to do this, but one day a
system upgrade left me with GNOME 3 permanently in fallback mode, in
which shell extensions don't seem to work. So I wrote this to replace
it.)

* system requirements

- Unix
- X11
- Xinerama information support (you don't need to be using Xinerama,
  but the system needs to expose a Xinerama-style screen list - I
  believe this is standard, even if you're using something like XRandR
  or NVidia's TwinView)

* "download"

This is Unix, so you get to build it yourself.

1. Clone repo

2. =make=

The binary is called =xdispswitch=.

* "installation"

This is Unix, so you get to figure it out on your own...

For GNOME 3's fallback mode: go to the /Applications/ menu, /System
Tools/, /Preferences/, /System/. Visit the /Keyboard/ section,
/Shortcuts/ tab, and select /Custom Shortcuts/. Click the + button to
add a new shortcut and put the path to your compiled =xdispswitch=
(e.g., =/home/tom/github/xdispswitch/xdispswitch=) in the Command
field. Then give it a shortcut.

I think non-fallback GNOME 3 was quite similar.

Other modern window managers and/or shells probably have very similar
functionality.

Other options (that I've never tried) might be:

- [[https://code.google.com/p/autokey/][autokey]]

- [[https://github.com/polyethene/IronAHK][IronAHK]]

* Command line options

Specify =-h= to get brief command line help.

Specify =-v= to have =xdispswitch= print stuff to stdout.

Specify =-l FILE= to have =xdispswitch= append stuff to a file called
=FILE=. (This file will grow indefinitely - so best put it in /tmp.)

* known bugs/issues

- Don't know if the code to detect docking windows - task bar, system
  menu, etc. - is quite right. (Though it works for the GNOME panels.)
  Worst result if it goes wrong is the window ending up underneath a
  docked one, and/or the position and size being slightly wrong.

- Windows that quantize their size (e.g., emacs, terminator) don't
  always go back to their original size after being moved from a
  larger monitor to a smaller and then back again.

- Probably many more I haven't found yet.

* see also...

[[https://github.com/tom-seddon/dispswitch][=dispswitch=]], a very similar program for Windows.
